apiVersion: v1
kind: Namespace
metadata:
  name: user1
spec: {}
status: {}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1
  namespace: user1
rules:
- apiGroups: ["", "extensions", "apps", "networking.k8s.io", "policy"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  - networkpolicies
  - poddisruptionbudgets
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: user1
  namespace: user1
subjects:
- kind: ServiceAccount
  name: ce-user1
  namespace: user1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: user1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ce-user1
  namespace: user1


